spring:
  application:
    name: user

server:
  port: 8888

with-ribbon:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:8095
    ServerListRefreshInterval: 15000